const mongoose = require('mongoose');

const ClothsSchema = mongoose.Schema([
    {
        id:Number,
        latest:Boolean,
        gender:String,
        category:String,
        type: String,
        brand:String,
        price:String,
        color:String,
        name:String,
        imgUrl:String,
        size:String,
        specifications:{
            fabric:String,
            ength:String,
            pattern:String,
            occasion:String
        },
        description:String
    },
    {
        id:Number,
        latest:Boolean,
        gender:String,
        category:String,
        type: String,
        brand:String,
        price:String,
        color:String,
        name:String,
        imgUrl:String,
        size:String,
        specifications:{
            fabric:String,
            ength:String,
            pattern:String,
            occasion:String
        },
        description:String
    },
    {
        id:Number,
        latest:Boolean,
        gender:String,
        category:String,
        type: String,
        brand:String,
        price:String,
        color:String,
        name:String,
        imgUrl:String,
        size:String,
        specifications:{
            fabric:String,
            ength:String,
            pattern:String,
            occasion:String
        },
        description:String
    },
    {
        id:Number,
        latest:Boolean,
        gender:String,
        category:String,
        type: String,
        brand:String,
        price:String,
        color:String,
        name:String,
        imgUrl:String,
        size:String,
        specifications:{
            fabric:String,
            ength:String,
            pattern:String,
            occasion:String
        },
        description:String
    },
    {
        id:Number,
        latest:Boolean,
        gender:String,
        category:String,
        type: String,
        brand:String,
        price:String,
        color:String,
        name:String,
        imgUrl:String,
        size:String,
        specifications:{
            fabric:String,
            ength:String,
            pattern:String,
            occasion:String
        },
        description:String
    },
    {
        id:Number,
        latest:Boolean,
        gender:String,
        category:String,
        type: String,
        brand:String,
        price:String,
        color:String,
        name:String,
        imgUrl:String,
        size:String,
        specifications:{
            fabric:String,
            ength:String,
            pattern:String,
            occasion:String
        },
        description:String
    },
    {
        id:Number,
        latest:Boolean,
        gender:String,
        category:String,
        type: String,
        brand:String,
        price:String,
        color:String,
        name:String,
        imgUrl:String,
        size:String,
        specifications:{
            fabric:String,
            ength:String,
            pattern:String,
            occasion:String
        },
        description:String
    },
    {
        id:Number,
        latest:Boolean,
        gender:String,
        category:String,
        type: String,
        brand:String,
        price:String,
        color:String,
        name:String,
        imgUrl:String,
        size:String,
        specifications:{
            fabric:String,
            ength:String,
            pattern:String,
            occasion:String
        },
        description:String
    },
    {
        id:Number,
        latest:Boolean,
        gender:String,
        category:String,
        type: String,
        brand:String,
        price:String,
        color:String,
        name:String,
        imgUrl:String,
        size:String,
        specifications:{
            fabric:String,
            ength:String,
            pattern:String,
            occasion:String
        },
        description:String
    },
    {
        id:Number,
        latest:Boolean,
        gender:String,
        category:String,
        type: String,
        brand:String,
        price:String,
        color:String,
        name:String,
        imgUrl:String,
        size:String,
        specifications:{
            fabric:String,
            ength:String,
            pattern:String,
            occasion:String
        },
        description:String
    },{
        id:Number,
        latest:Boolean,
        gender:String,
        category:String,
        type: String,
        brand:String,
        price:String,
        color:String,
        name:String,
        imgUrl:String,
        size:String,
        specifications:{
            fabric:String,
            ength:String,
            pattern:String,
            occasion:String
        },
        description:String
    },
    {
        id:Number,
        latest:Boolean,
        gender:String,
        category:String,
        type: String,
        brand:String,
        price:String,
        color:String,
        name:String,
        imgUrl:String,
        size:String,
        specifications:{
            fabric:String,
            ength:String,
            pattern:String,
            occasion:String
        },
        description:String
    },
    {
        id:Number,
        latest:Boolean,
        gender:String,
        category:String,
        type: String,
        brand:String,
        price:String,
        color:String,
        name:String,
        imgUrl:String,
        size:String,
        specifications:{
            fabric:String,
            ength:String,
            pattern:String,
            occasion:String
        },
        description:String
    },
    {
        id:Number,
        latest:Boolean,
        gender:String,
        category:String,
        type: String,
        brand:String,
        price:String,
        color:String,
        name:String,
        imgUrl:String,
        size:String,
        specifications:{
            fabric:String,
            ength:String,
            pattern:String,
            occasion:String
        },
        description:String
    },
    {
        id:Number,
        latest:Boolean,
        gender:String,
        category:String,
        type: String,
        brand:String,
        price:String,
        color:String,
        name:String,
        imgUrl:String,
        size:String,
        specifications:{
            fabric:String,
            ength:String,
            pattern:String,
            occasion:String
        },
        description:String
    },{
        id:Number,
        latest:Boolean,
        gender:String,
        category:String,
        type: String,
        brand:String,
        price:String,
        color:String,
        name:String,
        imgUrl:String,
        size:String,
        specifications:{
            fabric:String,
            ength:String,
            pattern:String,
            occasion:String
        },
        description:String
    },
    {
        id:Number,
        latest:Boolean,
        gender:String,
        category:String,
        type: String,
        brand:String,
        price:String,
        color:String,
        name:String,
        imgUrl:String,
        size:String,
        specifications:{
            fabric:String,
            ength:String,
            pattern:String,
            occasion:String
        },
        description:String
    },
    {
        id:Number,
        latest:Boolean,
        gender:String,
        category:String,
        type: String,
        brand:String,
        price:String,
        color:String,
        name:String,
        imgUrl:String,
        size:String,
        specifications:{
            fabric:String,
            ength:String,
            pattern:String,
            occasion:String
        },
        description:String
    },
    {
        id:Number,
        latest:Boolean,
        gender:String,
        category:String,
        type: String,
        brand:String,
        price:String,
        color:String,
        name:String,
        imgUrl:String,
        size:String,
        specifications:{
            fabric:String,
            ength:String,
            pattern:String,
            occasion:String
        },
        description:String
    },
    {
        id:Number,
        latest:Boolean,
        gender:String,
        category:String,
        type: String,
        brand:String,
        price:String,
        color:String,
        name:String,
        imgUrl:String,
        size:String,
        specifications:{
            fabric:String,
            ength:String,
            pattern:String,
            occasion:String
        },
        description:String
    }
])

const ClothModel = new mongoose.model('Cloths', ClothsSchema);

module.exports = ClothModel;